// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using planera_ledighet.api;

#nullable disable

namespace planera_ledighet.api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260327200619_AddUiConfig")]
    partial class AddUiConfig
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("planera_ledighet.api.Absence", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AbsenceCategoryId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationDays")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AbsenceCategoryId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Absences");
                });

            modelBuilder.Entity("planera_ledighet.api.AbsenceCategory", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AbsenceCategorys");
                });

            modelBuilder.Entity("planera_ledighet.api.Employee", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TeamId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("planera_ledighet.api.Team", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("planera_ledighet.api.UiConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("BlockPastDays")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CellWidth")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DisableDeletion")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RowHeight")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SidebarWidthCompact")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SidebarWidthFull")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SidebarWidthHidden")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("UiConfigs");
                });

            modelBuilder.Entity("planera_ledighet.api.Absence", b =>
                {
                    b.HasOne("planera_ledighet.api.AbsenceCategory", "AbsenceCategory")
                        .WithMany("Absences")
                        .HasForeignKey("AbsenceCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("planera_ledighet.api.Employee", "Employee")
                        .WithMany("Absences")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AbsenceCategory");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("planera_ledighet.api.Employee", b =>
                {
                    b.HasOne("planera_ledighet.api.Team", "Team")
                        .WithMany("Employees")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("planera_ledighet.api.AbsenceCategory", b =>
                {
                    b.Navigation("Absences");
                });

            modelBuilder.Entity("planera_ledighet.api.Employee", b =>
                {
                    b.Navigation("Absences");
                });

            modelBuilder.Entity("planera_ledighet.api.Team", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
